openapi: 3.0.2
info:
  title: Kotling + Swagger
  description: "Tutorials para utilizar o Kotling + Swagger"
  termsOfService: http://swagger.io/terms/
  contact:
    email: morrice256
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1-SNAPSHOT
tags:
  - name: user
    description: Operações com usuarios

paths:
  /user:
    post:
      tags:
        - user
      summary: Criar usuario
      description: Criar usuario
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      security:
        - user_auth:
            - write:user
            - read:user
  /user/{id}:
    get:
      tags:
        - user
      summary: Buscar usuario por ID
      description: Retornar um usuario
      operationId: findOne
      parameters:
        - name: id
          in: path
          description: ID do usuario
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Id invalido
        '404':
          description: Usuario não encontrado
      security:
        - api_key: []
        - usuario_auth:
            - write:usuario
            - read:usuario
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
        password:
          type: string

  securitySchemes:
    keycloak_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://localhost:8080/realms/KotlinDemo/protocol/openid-connect/token
          scopes:
            write:users: modify users
            read:users: read users
    api_key:
      type: apiKey
      name: api_key
      in: header